# Generated by Django 3.1.7 on 2021-03-27 21:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=4096, verbose_name='题目')),
                ('subject_class', models.CharField(default='', max_length=64, verbose_name='科目')),
                ('subject_unswer', models.CharField(max_length=4096, verbose_name='答案')),
                ('score', models.CharField(max_length=64, verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=128, verbose_name='试卷标题类名')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='结束时间')),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
                ('translate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.translateclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_answer', models.CharField(default='', max_length=4096, verbose_name='学生答案')),
                ('is_commit', models.IntegerField(blank=True, default=-1, verbose_name='是否提交（0否， 1是）')),
                ('user_score', models.FloatField(default=-1, verbose_name='用户评分')),
                ('auto_score', models.FloatField(default=-1, verbose_name='自动评分')),
                ('is_auto_score', models.IntegerField(default=-1, verbose_name='自动评分是否确认（0否， 1是）')),
                ('is_teacher_score', models.IntegerField(default=-1, verbose_name='老师是否评分（0否， 1是）')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
                ('translate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.translateclass')),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
