# Generated by Django 3.2.3 on 2022-03-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.IntegerField(default=1, verbose_name='1：问答题 2：选择题 3：填空题 4：判断题'),
        ),
    ]
