# Generated by Django 3.2.3 on 2022-04-21 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220421_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecordingscreen',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间'),
        ),
    ]
