# Generated by Django 3.2.3 on 2022-05-04 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_studentrecordingscreen_insert_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrecordingscreen',
            options={'verbose_name_plural': '录屏表'},
        ),
        migrations.AlterModelOptions(
            name='studentsubject',
            options={'verbose_name_plural': '学生题目'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '题库'},
        ),
        migrations.AlterModelOptions(
            name='translate',
            options={'verbose_name_plural': '试卷题目'},
        ),
        migrations.AlterModelOptions(
            name='translateclass',
            options={'verbose_name_plural': '试卷分类'},
        ),
        migrations.AddField(
            model_name='subject',
            name='insert_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='插入时间'),
        ),
        migrations.AlterField(
            model_name='studentrecordingscreen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='auto_score',
            field=models.FloatField(default=0, verbose_name='自动评分'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='user_score',
            field=models.FloatField(default=0, verbose_name='用户评分'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.TextField(max_length=4096, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='translateclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
